### ISSUE TITLE
delete parameter on the javascript minifier

### ISSUE THREAD

**Issue by vzsoft** [failwyn/BundlerMinifier#26]
### Installed product versions
- Visual Studio: 2022
- This extension: 2.9.9

### Description
delete parameter on the javascript minifier

### Steps to recreate
i need this code to minifier
```javascript
var funcObject2 = ({ param1, param2=1 }) => {
    console.log(param1);
    console.log(param2);
}
```

### Current behavior
wrong result:
```javascript
var funcObject2=({param1:n,t=1})=>{console.log(n),console.log(t)};
```
minifier delete "param2"! 

### Expected behavior
correct result:
```javascript
var funcObject2=({param1:n,param2:t=1})=>{console.log(n),console.log(t)};
```

thank you

**Comment by failwyn** [comment]
This looks like an issue with NUglify, would you mind posting an issue there and linking it here?

**Comment by vzsoft** [comment]
posted [NUglify issues](https://github.com/trullock/NUglify/issues/367)

**Comment by failwyn** [comment]
Thanks, I'll keep an eye on the issue and update the reference as soon as it's fixed.

**Comment by avera2011** [comment]
well, i think that the problem is change the name of named parameters,  my case:
i have this func:
`RenderForm = function ({ div_destino_id="", CustomHTMLBefore = "", ....`
and is used this way:
`f.RenderForm( { div_destino_id: "div_list", CustomHtmlAfter:""});`
after minif all the parameters have the default values (""), because the div_destino change to "n"
`RenderForm = function({r="", n="",`

**Comment by failwyn** [comment]
2.9.10 is now available if you want to check this issue
