### ISSUE TITLE
Bundling and Minifying From The Task Runner Explorer no Longer Works After Updating to Version 2.9.10

### ISSUE THREAD

**Issue by TheFurryMonk** [failwyn/BundlerMinifier#37]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Community 2022 17.10.5
- This extension: 2.9.10
- Project .NET Framework: .NET 4.8

### Description
After updating to the latest version, updating the bundle files from Task Runner Explorer results to the following error:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at BundlerMinifier.BundleHandler.TryGetBundles(String configFile, IEnumerable`1& bundles)
   at BundlerMinifierConsole.Program.GetConfigFileFromArgs(String[] args, String& configPath)
   at BundlerMinifierConsole.Program.Main(String[] args)

### Steps to recreate
1. After Visual Studio loads, right-click "bundleconfig.json -> Update all files" then click "Run" in the Task Runner Explorer
2. See the error message in the output console of the Task Runner Explorer

### Current behavior
After attempting to bundle and minify all files from the Task Runner Explorer, the output console displays a "System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0'" error then exits with "Process terminated with code -532462766."

![image](https://github.com/user-attachments/assets/ad646c21-ce0d-485b-9d02-f92925bf15bf)

### Expected behavior
It should start the bundling and modification process of all files registered in bundleconfig.json

Is there a way to revert to the previous version? The VS Marketplace nor the VS Extension Manager in Visual Studio 2022 does not seem to offer a way to do this.

**Comment by MaciekSiedlaczek** [comment]
The same issue noticed in VS 2022 Pro

**Comment by MaciekSiedlaczek** [comment]
The same issue noticed today. VS 2022 Pro

**Comment by failwyn** [comment]
What version of .Net is your project targeting?

**Comment by TheFurryMonk** [comment]
@failwyn The full .Net Framework 4.8

**Comment by failwyn** [comment]
Thanks, I'm looking at this now, I'll publish a hotfix asap

**Comment by failwyn** [comment]
@TheFurryMonk That's a good idea, I have multiple versions saved locally; I'll look into putting them up. The only think is I'm not sure if BundleOnBuild will target the correct version of the nuget package, I think it might look for the latest release instead of the one that matches the visx version.

**Comment by failwyn** [comment]
I found the issue, publishing a new version now.

When I upgraded the included version of newtonsoft.json.dll I grabbed the one compiled for .net6 instead of .net48. Apologies for the inconvenience; I will start maintaining the releases here to make it easier to roll back.

I'll also look into releasing prerelease version here for testing prior to publishing to the marketplace.

**Comment by TheFurryMonk** [comment]
@failwyn You are a lifesaver! I just tested the latest version and can confirm that it fixed the wrong dll version error. I am closing this issue now. 

P.S.
I hope the past vsix releases work without the possible BundleOnBuild issue.
